### PR TITLE
New look and feel

### PR DESCRIPTION
**Pull request by i582**
# Why

I don't like the current look and feel of the Playground, as well as the editor, so I figured this was an excuse to make a new design with a more responsive editor.

# What

What can it do that the current Playground can't?

- Sharing code by link
- Ability to comment code by Ctrl + /
- Ctrl + S not triggered page save
- More responsive code editor
- More beautiful interface
- More convenient keyboard control
- Focused on reusability, I plan to make it possible to embed it anywhere (for example, on the main page so that the user can run the example right there)

# Example

playground

# Try

See https://pmakhnev.tech/ for example.

# Some technical notes

Most of the server code remains the same, but I add a feature to save the code to a local database. The implementation is quite primitive, and if you have any suggestions on how to improve it, I will be glad to hear.

### CODE REVIEW

**Comment by i582** [comment]
Now links for sharing are passed through `?query=<hash>`, I think it would be cool to make links like `play.vlang.io/<hash>` on the server side. @medvednikov if you do it on the server side, I'll fix the link that the playground shows.

Also perhaps we could use a shorter hash? It seems to me that at the moment it is possible and will make links shorter and more convenient.

**Comment by medvednikov** [comment]
Amazing work, thanks! Merged and deployed.

Go playground uses 13 char strings like `-MKUWeDBml7`. We can definitely use short hashes for now.

**Comment by Sarctiann** [comment]
I like too, but i think that Ctrl+ / Ctrl- aren't a good key binding, because chrome already use them. Maybe you can add some config button, or change the key binding, or both.
nice work by the way!

**Comment by Sarctiann** [comment]
also, if i want to use it in my smartphone, I need that options, because I haven't the CTRL key :(

**Pull request merged**
